services:
  node1:
    build: .
    volumes:
      - ./keys:/app/keys
    command: ["./server_main", "8081", "1", "/app/keys/node1.key", "http://node2:8082", "http://node3:8083"]
    ports:
      - "8081:8081"

  node2:
    build: .
    volumes:
      - ./keys:/app/keys
    command: ["./server_main", "8082", "2", "/app/keys/node2.key", "http://node1:8081", "http://node3:8083"]
    ports:
      - "8082:8082"

  node3:
    build: .
    volumes:
      - ./keys:/app/keys
    command: ["./server_main", "8083", "3", "/app/keys/node3.key", "http://node1:8081", "http://node2:8082"]
    ports:
      - "8083:8083"